### ISSUE TITLE
zabna

### ISSUE THREAD

**Issue by durka** [balningau/gimste#2]
Discussion of {zabna}.

**Comment by teleological** [comment]
Is {[zabna](../blob/master/gismu/z/zabna.txt)} up first? Or is this a test?

**Comment by gerkubergu** [comment]
It's a test :)

**Comment by gerkubergu** [comment]
I think the flow we imagine is that the words up for discussion will have (basically empty) issues created like this one. They will be tied together by a milestone (one each week, but if a word is taking too long we can reassign it to a different mielstone). Proposals and discussion thereof will be under pull requests on the individual gismu files. When this issue is cross-referenced in a pull request, Github will automatically link it in, so coming here you'll see all the active {zabna} proposals.

pei

**Comment by solpahi** [comment]
la gerkubergu cu cusku di'e

> It's a test :)

ca'e Testing direct reply via email.

**Comment by durka** [comment]
.ua xu do pilno lo lojbo ke mrilu samru'e

**Comment by solpahi** [comment]
la'o me. Alex Burka .me cusku di'e

> .ua xu do pilno lo lojbo ke mrilu samru'e

ie lojbo su'o da
